services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: best_route_web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - bestroute-app-network

  test:
    image: mcr.microsoft.com/playwright:v1.61.1-noble
    container_name: best_route_web_test
    working_dir: /app
    ports:
      - "3001:3001"
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - bestroute-app-network

networks:
  bestroute-app-network:

volumes:
  playwright-cache:
