FROM mcr.microsoft.com/playwright:v1.61.1-jammy

WORKDIR /app

COPY package*.json ./

RUN npm install && npx playwright install

COPY src/ ./src/
RUN chown -R pwuser:pwuser /app

USER pwuser

CMD ["npm", "test"]