services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: best_route_web
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - bestroute-app-network
      - bestroute-shared-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: best_route_web_test
    ipc: host
    ports:
      - "9322:9322"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=test
      - PLAYWRIGHT_BASE_URL=http://web:3000
    stdin_open: true
    tty: true
    command: npx playwright test
    networks:
      - bestroute-app-network

networks:
  bestroute-app-network:
  bestroute-shared-network:
    external: true
