FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache bash \
    && addgroup -S appgroup \
    && adduser -S appuser -G appgroup

COPY package*.json ./

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]